### ISSUE TITLE
crash in ListRdsClusterEndpoint

### ISSUE THREAD

**Issue by chris-kiick-sp** [jckuester/awsls#43]
command:  awsls --debug -r us-east-1 --json 'aws_rds_cluster*'

output:

   • resource type not (yet) supported: aws_rds_cluster_instance
   • created new instance of AWS client region=us-east-1
   • found already installed Terraform provider name=aws path=/Users/REDACTED/.awsls/terraform-provider-aws_v3.42.0_x5 version=3.42.0
   • start launching new instance of Terraform AWS Provider profile= region=us-east-1
   • launched new instance of Terraform AWS Provider profile= region=us-east-1
   • start listing resources   profile= region=us-east-1 type=aws_rds_cluster
[REDACTED]
   • start listing resources   profile= region=us-east-1 type=aws_rds_cluster_endpoint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x760c6dd]

goroutine 131 [running]:
github.com/jckuester/awsls/aws.ListRdsClusterEndpoint(0x907fb00, 0xc000128000, 0xc00053bba8, 0x1, 0x1, 0x0, 0x0, 0xc0007dcc80)
	/home/jan/git/github.com/jckuester/awsls/aws/aws_rds_cluster_endpoint.go:27 +0x11d
github.com/jckuester/awsls/aws.ListResourcesByType(0x907fb00, 0xc000128000, 0xc00053bba8, 0x8429b75, 0x18, 0x107997e, 0xafa3630, 0xc000122150, 0x83d5939, 0x7)
	/home/jan/git/github.com/jckuester/awsls/aws/list.go:410 +0x8492
github.com/jckuester/awsls/resource.ListInMultipleAccountsAndRegions.func1(0xc0007204b0, 0xc00002cd80, 0x907fb00, 0xc000128000, 0x8429b75, 0x18, 0xc00196fef0, 0xc0004da1e0, 0xc000517d00, 0xc0007209e0, ...)
	/home/jan/git/github.com/jckuester/awsls/resource/list.go:58 +0x30a
created by github.com/jckuester/awsls/resource.ListInMultipleAccountsAndRegions
	/home/jan/git/github.com/jckuester/awsls/resource/list.go:45 +0x25f

**Comment by jckuester** [comment]
Thanks @chris-kiick-sp for reporting this issue! I didn't expect `*r.ClusterIdentifier` to be `nil` at any time. I probably have to add a nil check here. I'll come back to you when this is fixed!
